### ISSUE TITLE
Inquiry 

### ISSUE THREAD

**Issue by beatsbymeh** [romix123/MicroFreak-BatteryPack#1]
I see that you were making these in small batches, are you still currently doing that? If so… I’d 100% be interested in obtaining one of these.

**Comment by romix123** [comment]
Yes, i do. Contact me at ronaldleenes at icloud.com to make arrangementsVerstuurd vanaf mijn iPadOp 23 jan 2024 om 22:49 heeft beatsbymeh ***@***.***> het volgende geschreven:﻿
I see that you were making these in small batches, are you still currently doing that? If so… I’d 100% be interested in obtaining one of these.
